[package]
name = "sciproj-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { version = "1.0.97", features = ["backtrace"] }
sciproj = { path = "../sciproj" }
clap = { version = "4.5.32", features = ["derive"] }
csv = "1.3.1"
futures = "0.3.31"
itertools = "0.13"
log = "0.4.27"
rayon = "1.11.0"
schemars = "1.0.4"
scidev = { path = "../scidev" }
serde = { version = "1.0.219", features = ["derive"] }
serde_norway = "0.9"
serde_json = "1.0.140"
thiserror = "1.0.63"
tokio = { version = "1.0", features = ["full"] }
walkdir = "2.5.0"

[lints]
workspace = true

[[bin]]
name = "scidev"
path = "src/main.rs"
