[package]
name = "sciproj"
version = "0.0.0"
edition = "2024"

[dependencies]
anyhow = { version = "1.0.97", features = ["backtrace"] }
futures = "0.3.31"
itertools = "0.13"
log = "0.4.27"
rayon = "1.11.0"
schemars = "1.0.4"
scidev = { path = "../scidev" }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
thiserror = "1.0.63"
tokio = { version = "1.0", features = ["full"] }
walkdir = "2.5.0"
tempfile = "3.19.1"
toml = "0.9.8"

[lints]
workspace = true
