[package]
name = "sciproj"
version = "0.1.0"
edition = "2024"

[dependencies]
scidev = { workspace = true }
toml = "0.9.8"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.145"
tempfile = "3.23.0"

[dev-dependencies]
clap = "4.5"

[lints]
workspace = true
